### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by keithtobin** [alexa/skill-sample-nodejs-city-guide#1]
Are we missing a package.json form the src directory?

**Comment by jeffblankenburg** [comment]
Yes.  Thank you.  I just added it!

**Comment by bkdargan** [comment]
First off, let me say awesome job and thank you for sharing the information.  I am trying to recreate this code, but keep getting the following error.

The remote endpoint could not be called, or the response it returned was invalid.

Any idea why this is happening?  Thanks again.
