### ISSUE TITLE
getOverview

### ISSUE THREAD

**Issue by chaanmaan** [alexa/skill-sample-nodejs-city-guide#6]
I'm new at this but I found that the getOverview Intent did not work until I copied/added the getOverview method into the var newSessionHandlers section in index.js.

**Comment by devuserroyy** [comment]
I had to make changes in startSearchHandlers.
Before :
'getOverview': function () {

        output = locationOverview;

        this.emit(':tellWithCard', output, output, locationOverview);

    },
After:
'getOverview': function () {

        output = locationOverview;

       this.emit(':tellWithCard', output, location, locationOverview);

    },
